### ISSUE TITLE
レジスタの値を目的のレジスタに代入できない

### ISSUE THREAD

**Issue by masato-ka2** [ytakano-lecture/aa64emu#1]
NAISTの川島です．

https://github.com/ytakano-lecture/aa64emu/blob/2b33a3e1ab46133a1b9e475b7ddb3a81d9a7da47/src/eval.rs#L89-L99
96行目のrは，代入するレジスタ名，dstにする必要があるのではないでしょうか？

```
- ctx.set_reg(r, n);
+ ctx.set_reg(dst, n);
```
上記のように変更し，コードを実行した結果，レジスタの値を目的のレジスタに代入できるようになりました．

**Comment by ytakano** [comment]
ありがとうございます。修正しました。
